### ISSUE TITLE
1.21 (fabric) uncraftable.

### ISSUE THREAD

**Issue by Ynaught** [asasinmode/wheelbarrow#5]
It shows up as an item in REI. The recipe formatting seems correct. Not sure what the issue is. I know datapacks changed alot of the tile formatting to take plural named folders to make them sigular. So I'ma test if the issue is if the folder is supposed to be recipe instead of recipes.

**Comment by Ynaught** [comment]
Yup, that was the issue. You need to rename your folder from "recipes" to "recipe".

And additional request, when you do upload the new file, please give the mod file an actual name so it's easier for players to find when troubleshooting. 😅

**Comment by asasinmode** [comment]
You are right, I missed that part in fabric 1.21 release blog. Should be fixed in `1.0.2`, close the issue if it works for you

My bad for the 1.21 mod file having no name in the filename. I did that release manually and forgot that part of the name, will fix

**Comment by asasinmode** [comment]
Actually I'm just going to delete the `1.0.1` version for 1.21 since it's broken and there is no way for me to reupload the file without deleting the whole release and remaking it. It causes it to be higher up the list than the newest one which I find confusing.
Thanks again for reporting

**Comment by Ynaught** [comment]
> My bad for the 1.21 mod file having no name in the filename. I did that release manually and forgot that part of the name, will fix

_"v1.0.2+fabric_1.21"_ is still not a name. I meant something like _"Copper_Wheelbarrow_v1.0.2+fabric_1.21"_

I asked this because when looking at something like this: 

![image](https://github.com/asasinmode/wheelbarrow/assets/32611591/285bd7b3-f3f2-4f9b-bd88-2d084a4d0465)

it becomes very much annoying having to look up an index trying to figure out which one is yours. 😅 

Either way, despite that small cavoite, I am happy to help. Alot of mod devs missed the memo apparently. There's alot more "plural to single" changes mojang did for no reason what so ever. And there's no comprehnsive list out there that states all that is changed. All I know is "tags" is still plural.

**Comment by asasinmode** [comment]
The `1.0.2` version's filename, which is available to download on [modrinth](https://modrinth.com/mod/wheelbarrow/version/1.0.2) (curseforge still has it under review at the moment), is `wheelbarrow-1.0.2+fabric_1.21.jar`, the same convention older versions should fall under. As far as I know only v1.0.1 on minecraft 1.21 was under the wrong filename, thanks for help

**Comment by Ynaught** [comment]
Oh sorry, I must have read it wrong on the page. I double checked and you are right. My mistake. >.<

.

EDIT:
OHHHH, I see my issue. Modrinth is weird:
![image](https://github.com/asasinmode/wheelbarrow/assets/32611591/28e4145f-e9fb-461e-b7bd-caa07e5f520a)
I saw that and assumed that was the file name. Because why would they ever want their site to be consistant I guess. xD

Again, my apologies.

**Comment by Ynaught** [comment]
Side note, here's a list I was able to find to provide someone else incase you find it helpful:

structures -> structure

advancements -> advancement

recipes -> recipe

loot_tables -> loot_table

predicates -> predicate

item_modifiers -> item_modifier

functions -> function

tags/functions -> tags/function

tags/items -> tags/item

tags/blocks -> tags/block

tags/entity_types -> tags/entity_type

tags/fluids -> tags/fluid

tags/game_events -> tags/game_event


.

Above are the confirmed issues. This one however I was not able to confirm so IDK if this one was changed or not:
loot_tables/blocks - > loot_table/block

The others there 100% need to be fixed for a mod to not be broken. Idk about if the last one was changed though.
